version: '2'
services:
  monomorphist-1:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    env_file:
      - meteor.env.1
    volumes:
      - /opt/monomorphist/monoserver:/bundle
      - /opt/monomorphist/mononodes/:/mononodes
      - /opt/monomorphist/volume/src/:/src
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "traefik.backend=monomorphist"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.backend.loadbalancer.sticky=true"
      - "traefik.backend.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.4"
      - "traefik.docker.network=monomorphist_default"
      - "traefik.frontend.rule=Host:mono.morph.ist"
      - "traefik.port=80"
    links:
      - "mongodb:mongodb"
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:5000"
        tag: "monomorphist-meteor-1"

  monomorphist-2:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    env_file:
      - meteor.env.2
    volumes:
      - /opt/monomorphist/monoserver:/bundle
      - /opt/monomorphist/mononodes/:/mononodes
      - /opt/monomorphist/volume/src/:/src
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "traefik.backend=monomorphist"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.backend.loadbalancer.sticky=true"
      - "traefik.backend.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.4"
      - "traefik.docker.network=monomorphist_default"
      - "traefik.frontend.rule=Host:mono.morph.ist"
      - "traefik.port=80"
    links:
      - "mongodb:mongodb"
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:5000"
        tag: "monomorphist-meteor-2"

  monomorphist-3:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 80
    env_file:
      - meteor.env.3
    volumes:
      - /opt/monomorphist/monoserver:/bundle
      - /opt/monomorphist/mononodes/:/mononodes
      - /opt/monomorphist/volume/src/:/src
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
    labels:
      - "traefik.backend=monomorphist"
      - "traefik.backend.loadbalancer.method=drr"
      - "traefik.backend.loadbalancer.sticky=true"
      - "traefik.backend.circuitbreaker.expression=ResponseCodeRatio(500, 600, 0, 600) > 0.4"
      - "traefik.docker.network=monomorphist_default"
      - "traefik.frontend.rule=Host:mono.morph.ist"
      - "traefik.port=80"
    links:
      - "mongodb:mongodb"
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:5000"
        tag: "monomorphist-meteor-3"

  mongodb:
    image: mongo:3.2
    expose:
      - "27017"
    volumes:
      - /opt/monomorphist/mongodata:/data/db
      - /opt/monomorphist/volume/src:/src
    restart: always
    labels:
      - "traefik.docker.network=monomorphist_default"
    logging:
      driver: "syslog"
      options:
        syslog-address: "udp://localhost:5000"
        tag: "monomorphist-mongo"

networks:
  default:
    external:
      name: traefik_traefik_enabled
