parser: babel-eslint
parserOptions:
  allowImportExportEverywhere: true
  ecmaVersion: 6

plugins:
  - babel
  - import

extends:
  - airbnb-base

env:
  es6: true
  node: true

rules:
  max-len: [2, 150, 2, { ignoreUrls: true, ignoreComments: false }]
  no-underscore-dangle: 0
